apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mongodb
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      name: mongodb
    name: mongo-data-mongodb-0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      name: mongodb
    name: mongo-data-mongodb-1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      name: mongodb
    name: mongo-data-mongodb-2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      name: mongodb
    name: mongodb
  spec:
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    creationTimestamp: null
    labels:
      app: mongodb
      name: mongodb
    name: mongodb-internal
  spec:
    clusterIP: None
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: mongodb
      name: mongodb
    name: mongodb
  spec:
    podManagementPolicy: OrderedReady
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        name: mongodb
    serviceName: mongodb-internal
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mongodb
          name: mongodb
      spec:
        containers:
        - args:
          - run-mongod-replication
          env:
          - name: MONGODB_DATABASE
            value: parks
          - name: MONGODB_USER
            value: mongodb
          - name: MONGODB_PASSWORD
            value: mongodb
          - name: MONGODB_ADMIN_PASSWORD
            value: mongodb
          - name: MONGODB_REPLICA_NAME
            value: rs0
          - name: MONGODB_KEYFILE_VALUE
            value: "12345678901234567890"
          - name: MONGODB_SERVICE_NAME
            value: mongodb-internal
          image: registry.access.redhat.com/rhscl/mongodb-34-rhel7:latest
          imagePullPolicy: Always
          name: mongo-container
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - stat
              - /tmp/initialized
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongo-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          app: mongodb
          name: mongodb
        name: mongo-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
      status:
        phase: Pending
  status:
